config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "health" => "health#index"
    get "stats"  => "health#stats"

    resources :messages
    root to: "messages#index"
  end

  get "config"                            => "utilities#configuration"
  get "/ElbHealthCheck"                   => "utilities#elb_health_check"
  get "unit-types"                        => "utilities#unit_types"
  get "/"                                 => "utilities#root"

  post "/messages"                        => "messages#create"
  post "/messages/bulk_update"            => "messages_api#bulk_update"
  post "/messages/bulk_create"            => "messages_api#bulk_create"
  get  "/messages/search"                 => "messages_api#search"
  get  "/messages/:id"                    => "messages_api#show"
  post "/messages/:id"                    => "messages_api#update"

  get "/runtime_settings"                 => "runtime_settings_api#show"
  post "/runtime_settings"                => "runtime_settings_api#update"
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Concerns::BasicAuthentication

    before_action :populate_is_healthy

    def populate_is_healthy
      @is_healthy = HealthWatcher.new.healthy?
    end

    def read_from_database
      params[:use_master] ? :master : :replica
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def append_info_to_payload(payload)
    super
    if !request.get? || response.status.to_s[0] != "2"
      payload[:headers] = Hash[request.headers.select { |k, v| k.starts_with?("HTTP_") && (!k.include?("AUTH") || k.include?("USER_CONTEXT"))}]
      payload[:response] = response.body
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_sidebar.html.erb
<%#
# Sidebar

This partial is used to display the sidebar in Administrate.
By default, the sidebar contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<ul class="sidebar__list">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <% begin %>
    <li>
      <%= link_to(
        display_resource_name(resource),
        [namespace, resource],
        class: "sidebar__link sidebar__link--#{nav_link_state(resource)}"
      ) %>
    </li>
  <% rescue %>
  <% end %>
  <% end %>
  <li>
    <% if @is_healthy %>
      <b> <%= link_to('Healthy', admin_health_path) %> </b>
    <% else %>
      <b> <%= link_to('UNHEALTHY', admin_health_path, style: 'color: red;') %> </b>
    <% end %>
  </li>
</ul>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="Search"
      value="<%= search_term %>"
      aria-label="Search"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "New #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
  </div>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>